// Generated by Shared/Design/generate.py from Shared/Design/tokens.json. Do not edit.

package com.khushi.conduit.core.design

object DesignTokens {

    object Brand {
        const val NAME = "Conduit"
        const val TAGLINE = "Your Android, connected to your Mac."
    }

    /** Light and dark colours as opaque 0xAARRGGBB. */
    object Color {
        val accent = ColorToken(light = 0xFF4F5DFF, dark = 0xFF7B87FF)
        val accentPressed = ColorToken(light = 0xFF3E4AE0, dark = 0xFF6673F2)
        val onAccent = ColorToken(light = 0xFFFFFFFF, dark = 0xFF0B0D1F)
        val flow = ColorToken(light = 0xFF1FB5D8, dark = 0xFF3FD0EE)
        val background = ColorToken(light = 0xFFF5F6F8, dark = 0xFF0D0E12)
        val surface = ColorToken(light = 0xFFFFFFFF, dark = 0xFF16171D)
        val surfaceElevated = ColorToken(light = 0xFFFFFFFF, dark = 0xFF1D1F27)
        val surfaceMuted = ColorToken(light = 0xFFEDEEF2, dark = 0xFF22242D)
        val border = ColorToken(light = 0xFFE0E2E8, dark = 0xFF2B2E39)
        val textPrimary = ColorToken(light = 0xFF15161C, dark = 0xFFF2F3F7)
        val textSecondary = ColorToken(light = 0xFF5D6070, dark = 0xFFA2A5B4)
        val textTertiary = ColorToken(light = 0xFF8D90A0, dark = 0xFF6D7080)
        val statusConnected = ColorToken(light = 0xFF1FA971, dark = 0xFF3DD68C)
        val statusWorking = ColorToken(light = 0xFFD9912B, dark = 0xFFF2B551)
        val statusError = ColorToken(light = 0xFFDC3E45, dark = 0xFFFF6369)
        val statusIdle = ColorToken(light = 0xFF8D90A0, dark = 0xFF6D7080)
    }

    /** Corner radii in dp. */
    object Radius {
        const val small = 8
        const val medium = 12
        const val large = 16
        const val extraLarge = 28
    }

    /** Spacing in dp. */
    object Spacing {
        const val xxs = 2
        const val xs = 4
        const val s = 8
        const val m = 12
        const val l = 16
        const val xl = 24
        const val xxl = 32
        const val xxxl = 48
    }

    /** Type roles: size in sp and weight. */
    object Typography {
        val display = TypeRole(sizeSp = 32, weight = "medium")
        val title = TypeRole(sizeSp = 22, weight = "medium")
        val headline = TypeRole(sizeSp = 16, weight = "medium")
        val body = TypeRole(sizeSp = 16, weight = "regular")
        val callout = TypeRole(sizeSp = 14, weight = "regular")
        val caption = TypeRole(sizeSp = 12, weight = "regular")
    }

    object Motion {
        const val quickMs = 120
        const val standardMs = 220
        const val emphasizedMs = 360
    }

    object Feature {
        val mirroring = FeatureToken(id = "mirroring", title = "Screen mirroring", icon = "Cast")
        val remoteInput = FeatureToken(id = "remoteInput", title = "Control from Mac", icon = "Mouse")
        val trackpad = FeatureToken(id = "trackpad", title = "Phone as trackpad", icon = "TouchApp")
        val clipboard = FeatureToken(id = "clipboard", title = "Clipboard", icon = "ContentPaste")
        val camera = FeatureToken(id = "camera", title = "Phone camera", icon = "PhotoCamera")
        val calls = FeatureToken(id = "calls", title = "Calls", icon = "Call")
        val links = FeatureToken(id = "links", title = "Link sharing", icon = "Link")
        val audio = FeatureToken(id = "audio", title = "Audio", icon = "MusicNote")
        val files = FeatureToken(id = "files", title = "File sharing", icon = "Description")
        val notifications = FeatureToken(id = "notifications", title = "Notifications", icon = "Notifications")
        val findMac = FeatureToken(id = "findMac", title = "Find my Mac", icon = "LaptopMac")

        val all: List<FeatureToken> = listOf(
            mirroring,
            remoteInput,
            trackpad,
            clipboard,
            camera,
            calls,
            links,
            audio,
            files,
            notifications,
            findMac,
        )
    }

    /** Labels for feature availability, keyed by the protocol's raw value. */
    val availabilityLabel: Map<String, String> = mapOf(
        "available" to "Available",
        "active" to "Active",
        "requires_permission" to "Requires permission",
        "requires_setup" to "Needs setup",
        "disabled" to "Off",
        "unsupported" to "Not supported on this device",
        "planned" to "Planned",
    )

    object Term {
        const val connected = "Connected"
        const val notConnected = "Not connected"
        const val connecting = "Connecting…"
        const val reconnecting = "Reconnecting…"
        const val pairing = "Pairing…"
        const val disconnect = "Disconnect"
        const val reconnect = "Reconnect"
        const val pair = "Pair"
        const val forget = "Forget"
        const val mirrorScreen = "Mirror screen"
        const val useAsTrackpad = "Use phone as trackpad"
        const val useCamera = "Use phone camera"
        const val shareLink = "Share link"
        const val sendClipboard = "Send clipboard"
        const val callPhone = "Call from phone"
        const val findMac = "Find my Mac"
    }
}
