#!/usr/bin/env python3
"""
Generate Swift and Kotlin constants from tokens.json.

    python3 Shared/Design/generate.py          write the generated files
    python3 Shared/Design/generate.py --check  fail if they are out of date

tokens.json is the single source of truth for Conduit's brand system. The
generated files are committed so neither platform build needs Python.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TOKENS = json.loads((ROOT / "Shared/Design/tokens.json").read_text())

SWIFT_OUT = ROOT / "Shared/ConduitKit/Sources/ConduitDesign/Generated/DesignTokens.swift"
KOTLIN_OUT = ROOT / "Android/core/src/main/java/com/khushi/conduit/core/design/DesignTokens.kt"

HEADER = "Generated by Shared/Design/generate.py from Shared/Design/tokens.json. Do not edit."


def hex_rgb(value: str) -> str:
    return value.lstrip("#").upper()


def camel_to_const(name: str) -> str:
    return name


def swift() -> str:
    t = TOKENS
    lines = [f"// {HEADER}", "", "import CoreGraphics", "", "public enum DesignTokens {", ""]
    lines += ["    public enum Brand {",
              f'        public static let name = "{t["brand"]["name"]}"',
              f'        public static let tagline = "{t["brand"]["tagline"]}"',
              "    }", ""]
    lines += ["    /// Light and dark sRGB values as 0xRRGGBB.", "    public enum Color {"]
    for key, v in t["color"].items():
        lines.append(f"        public static let {key} = ColorToken(light: 0x{hex_rgb(v['light'])}, dark: 0x{hex_rgb(v['dark'])})")
    lines += ["    }", ""]
    lines += ["    public enum Radius {"]
    for key, v in t["radius"]["mac"].items():
        lines.append(f"        public static let {key}: CGFloat = {v}")
    lines += ["    }", ""]
    lines += ["    public enum Spacing {"]
    for key, v in t["spacing"].items():
        lines.append(f"        public static let {key}: CGFloat = {v}")
    lines += ["    }", ""]
    lines += ["    public enum Typography {"]
    for key, v in t["type"].items():
        mac = v["mac"]
        lines.append(f"        public static let {key} = TypeRole(size: {mac['size']}, weight: .{mac['weight']})")
    lines += ["    }", ""]
    lines += ["    public enum Motion {"]
    for key, v in t["motion"].items():
        lines.append(f"        public static let {key.replace('Ms', '')}: Double = {v / 1000}")
    lines += ["    }", ""]
    lines += ["    public enum Feature {"]
    for key, v in t["features"].items():
        lines.append(f'        public static let {key} = FeatureToken(id: "{key}", title: "{v["title"]}", symbol: "{v["symbolMac"]}")')
    lines += ["", "        public static let all: [FeatureToken] = ["]
    lines += [f"            {key}," for key in t["features"]]
    lines += ["        ]", "    }", ""]
    lines += ["    /// Labels for feature availability, keyed by the protocol's raw value.", "    public static let availabilityLabel: [String: String] = ["]
    lines += [f'        "{k}": "{v}",' for k, v in t["availability"].items()]
    lines += ["    ]", ""]
    lines += ["    public enum Term {"]
    for key, v in t["terms"].items():
        lines.append(f'        public static let {key} = "{v}"')
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def kotlin() -> str:
    t = TOKENS
    lines = [f"// {HEADER}", "", "package com.khushi.conduit.core.design", "", "object DesignTokens {", ""]
    lines += ["    object Brand {",
              f'        const val NAME = "{t["brand"]["name"]}"',
              f'        const val TAGLINE = "{t["brand"]["tagline"]}"',
              "    }", ""]
    lines += ["    /** Light and dark colours as opaque 0xAARRGGBB. */", "    object Color {"]
    for key, v in t["color"].items():
        lines.append(f"        val {key} = ColorToken(light = 0xFF{hex_rgb(v['light'])}, dark = 0xFF{hex_rgb(v['dark'])})")
    lines += ["    }", ""]
    lines += ["    /** Corner radii in dp. */", "    object Radius {"]
    for key, v in t["radius"]["android"].items():
        lines.append(f"        const val {key} = {v}")
    lines += ["    }", ""]
    lines += ["    /** Spacing in dp. */", "    object Spacing {"]
    for key, v in t["spacing"].items():
        lines.append(f"        const val {key} = {v}")
    lines += ["    }", ""]
    lines += ["    /** Type roles: size in sp and weight. */", "    object Typography {"]
    for key, v in t["type"].items():
        a = v["android"]
        lines.append(f'        val {key} = TypeRole(sizeSp = {a["size"]}, weight = "{a["weight"]}")')
    lines += ["    }", ""]
    lines += ["    object Motion {"]
    for key, v in t["motion"].items():
        lines.append(f"        const val {key} = {v}")
    lines += ["    }", ""]
    lines += ["    object Feature {"]
    for key, v in t["features"].items():
        lines.append(f'        val {key} = FeatureToken(id = "{key}", title = "{v["title"]}", icon = "{v["iconAndroid"]}")')
    lines += ["", "        val all: List<FeatureToken> = listOf("]
    lines += [f"            {key}," for key in t["features"]]
    lines += ["        )", "    }", ""]
    lines += ["    /** Labels for feature availability, keyed by the protocol's raw value. */", "    val availabilityLabel: Map<String, String> = mapOf("]
    lines += [f'        "{k}" to "{v}",' for k, v in t["availability"].items()]
    lines += ["    )", ""]
    lines += ["    object Term {"]
    for key, v in t["terms"].items():
        lines.append(f'        const val {key} = "{v}"')
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, content in ((SWIFT_OUT, swift()), (KOTLIN_OUT, kotlin())):
        if not path.parent.exists():
            continue  # that platform's module is not in the tree yet
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Out of date — run python3 Shared/Design/generate.py:")
        for p in stale:
            print(f"  {p}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
